import React from 'react';
import { BarChart3, Clock, TrendingUp, ChevronRight, Zap, ShieldCheck } from 'lucide-react';
import { PredictionResult } from '../types';

interface FeedViewProps {
  predictions: PredictionResult[];
  onSelectPrediction: (pred: PredictionResult) => void;
}

export const FeedView: React.FC<FeedViewProps> = ({ predictions, onSelectPrediction }) => {
  return (
    <main className="flex-1 p-6 sm:p-8 bg-gradient-to-b from-[#0a0a0a] to-[#050505] overflow-y-auto select-none">
      <div className="max-w-5xl mx-auto flex flex-col h-full">
        
        {/* Header */}
        <div className="flex items-end justify-between mb-8 pb-4 border-b border-white/10">
          <div>
            <h1 className="text-3xl font-bold tracking-tight mb-1 text-white flex items-center gap-3">
              <BarChart3 className="w-8 h-8 text-blue-500" />
              <span>Quant Market Feed</span>
            </h1>
            <p className="text-gray-400 text-sm">
              Live historical AI vision predictions generated by SportiQ quant neural engine.
            </p>
          </div>
          <div className="text-right hidden sm:block">
            <span className="text-xs font-mono px-3 py-1.5 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 font-bold">
              ● {predictions.length} ACTIVE SIGNALS
            </span>
          </div>
        </div>

        {/* Predictions Grid */}
        {predictions.length === 0 ? (
          <div className="flex-1 border-2 border-dashed border-white/10 rounded-2xl flex flex-col items-center justify-center p-12 text-center">
            <Clock className="w-12 h-12 text-gray-600 mb-3 animate-pulse" />
            <h3 className="text-base font-bold text-gray-400">No predictions recorded yet</h3>
            <p className="text-xs text-gray-600 mt-1">Upload a match picture in the AI Predictor tab to generate the first signal.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-12">
            {predictions.map((pred) => (
              <div
                key={pred.id}
                onClick={() => onSelectPrediction(pred)}
                className="border border-white/10 rounded-2xl bg-[#080808] hover:bg-white/[0.04] transition-all cursor-pointer p-6 flex flex-col justify-between shadow-xl relative overflow-hidden group hover:border-blue-500/40 transform hover:-translate-y-1"
              >
                {/* Top bar */}
                <div>
                  <div className="flex items-center justify-between gap-2 mb-3">
                    <span className="text-[10px] font-mono font-bold px-2.5 py-0.5 rounded bg-blue-500/15 text-blue-400 border border-blue-500/30">
                      {pred.competition}
                    </span>
                    <span className="text-[10px] font-mono text-gray-500 flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      <span>{pred.matchDate || 'Upcoming'}</span>
                    </span>
                  </div>

                  <h3 className="text-lg font-bold text-white group-hover:text-blue-400 transition-colors">
                    {pred.matchTitle}
                  </h3>

                  {/* Favour & BTTS pills */}
                  <div className="grid grid-cols-3 gap-2 my-4">
                    <div className="bg-white/5 p-2 rounded-lg border border-white/5">
                      <div className="text-[9px] text-gray-500 uppercase font-mono">Favour</div>
                      <div className="text-xs font-bold text-blue-400 truncate">{pred.favorite}</div>
                    </div>
                    <div className="bg-white/5 p-2 rounded-lg border border-white/5">
                      <div className="text-[9px] text-gray-500 uppercase font-mono">BTTS</div>
                      <div className={`text-xs font-bold font-mono ${pred.btts.prediction === 'Yes' ? 'text-emerald-400' : 'text-rose-400'}`}>
                        {pred.btts.prediction} ({pred.btts.probability}%)
                      </div>
                    </div>
                    <div className="bg-white/5 p-2 rounded-lg border border-white/5">
                      <div className="text-[9px] text-gray-500 uppercase font-mono">Confidence</div>
                      <div className="text-xs font-bold font-mono text-emerald-400">{pred.confidenceScore}%</div>
                    </div>
                  </div>

                  <div className="p-3 rounded-xl bg-blue-950/20 border border-blue-500/20 text-xs font-mono text-gray-200">
                    <span className="text-blue-400 font-bold mr-1">BET:</span>
                    <span>{pred.recommendedBet}</span>
                  </div>
                </div>

                <div className="mt-5 pt-3 border-t border-white/5 flex items-center justify-between text-[11px] text-gray-500 font-mono">
                  <span>Quant Quantified • {pred.createdBy}</span>
                  <span className="text-blue-400 flex items-center gap-1 group-hover:translate-x-1 transition-transform font-bold">
                    <span>View Matrix</span>
                    <ChevronRight className="w-3.5 h-3.5" />
                  </span>
                </div>

              </div>
            ))}
          </div>
        )}

      </div>
    </main>
  );
};
